# **Data Generator Testing**
This notebook demonstrates the necessary imports and setup to test the Data Generator. If you follow along with this notebook then you can test the Data Generator with our Amazing Grace audio data. The batches are generated as individual elements because of the inefficiency in reshaping audio data, but the generator still considerably improves performance.

Use the following commands to install the two libraries. ffmpeg is not used at this time but may be necessary later. Librosa allows us to easily read and process audio data.

In [2]:
!pip install librosa


In [3]:
!pip install ffmpeg


  Created wheel for ffmpeg: filename=ffmpeg-1.4-cp36-none-any.whl size=6083 sha256=b64e27acca988c10390126df0c8c6bf754a4d839e08ba48c7c93a0563e8a60e5
  Stored in directory: /root/.cache/pip/wheels/b6/68/c3/a05a35f647ba871e5572b9bbfc0b95fd1c6637a2219f959e7a
Successfully built ffmpeg


Verify directory structure and create directory for audio data.

In [4]:
ls

sample_data/


In [5]:
mkdir grace_data

In [6]:
ls

grace_data/  sample_data/


In [7]:
cd grace_data/

/content/grace_data


Use the following two commands to unpack the Amazing Grace data from the below URL and into the current directory, creating a subdirectory under grace_data called amazing_grace.

In [8]:
!wget https://ccrma.stanford.edu/damp/performances/amazing_grace/amazing_grace.tar.gz

--2020-10-09 17:14:38--  https://ccrma.stanford.edu/damp/performances/amazing_grace/amazing_grace.tar.gz
Resolving ccrma.stanford.edu (ccrma.stanford.edu)... 171.64.197.141
Connecting to ccrma.stanford.edu (ccrma.stanford.edu)|171.64.197.141|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 18757937250 (17G) [application/x-gzip]
Saving to: ‘amazing_grace.tar.gz’

amazing_grace.tar.g 100%[===================>]  17.47G  16.1MB/s    in 19m 51s 

2020-10-09 17:34:30 (15.0 MB/s) - ‘amazing_grace.tar.gz’ saved [18757937250/18757937250]



In [9]:
!tar xvzf amazing_grace.tar.gz

Streaming output truncated to the last 5000 lines.
amazing_grace/480850451_341022426.m4a
amazing_grace/48097497_3324168.m4a
amazing_grace/481090185_197615978.m4a
amazing_grace/481167633_192860366.m4a
amazing_grace/481187326_193186961.m4a
amazing_grace/481262354_192432997.m4a
amazing_grace/48135877_16052645.m4a
amazing_grace/48135877_234512676.m4a
amazing_grace/481378802_192543516.m4a
amazing_grace/481497482_193006549.m4a
amazing_grace/48153247_28462527.m4a
amazing_grace/481605101_193224801.m4a
amazing_grace/481639267_194285233.m4a
amazing_grace/48165633_8059972.m4a
amazing_grace/481694771_224163511.m4a
amazing_grace/481925016_201419795.m4a
amazing_grace/481925016_202209122.m4a
amazing_grace/482041591_211491911.m4a
amazing_grace/482041591_217870974.m4a
amazing_grace/482041591_222534578.m4a
amazing_grace/482041591_243091529.m4a
amazing_grace/482041591_249430120.m4a
amazing_grace/482108108_193710806.m4a
amazing_grace/482166128_268252478.m4a
amazing_grace/482177994_206487732.m4a
amazing_gr

Verify directory structure and presence of data.

In [10]:
%ls

amazing_grace/     amazing_grace.midi    amazing_grace.tsv
amazing_grace.m4a  amazing_grace.tar.gz


In [11]:
cd amazing_grace

/content/grace_data/amazing_grace


In [12]:
%ls

100013538_14906339.m4a   233364533_118608256.m4a  438791297_161017644.m4a
100030930_13364402.m4a   233364533_136937920.m4a  438911935_284945756.m4a
100051581_16289560.m4a   233445694_62180545.m4a   438933221_161613573.m4a
100112831_13200625.m4a   233448414_55781601.m4a   438933221_190308713.m4a
100118262_13452888.m4a   233466913_65953702.m4a   438964739_225422317.m4a
100119127_13195184.m4a   233472087_58875165.m4a   43897468_131018598.m4a
100125241_14688700.m4a   233518838_58638128.m4a   43897468_131030204.m4a
100128262_13604411.m4a   233565665_56427140.m4a   438984922_161602575.m4a
100144633_13209180.m4a   233596678_244113745.m4a  439008138_185232504.m4a
100144633_13209683.m4a   233596678_56053294.m4a   439061673_233712928.m4a
100157138_14224810.m4a   233596678_57431362.m4a   439088980_200216822.m4a
100166773_13285611.m4a   233596678_77129826.m4a   43911803_74265138.m4a
100174192_16147106.m4a   233650365_78226877.m4a   439194705_185567679.m4a
100177738_14633678.m4a   233652832_1250136

Import some more necessary libraries. If you are running this code locally it is assumed you have these installed but if not then use pip and install these popular libraries.

In [13]:
import numpy as np
import keras

import random
import librosa
from os import listdir
from os.path import isfile, join

Create list of files from the data and verify that list contains correct content.

In [14]:
file_list = [f for f in listdir(".") if isfile(join(".", f))]

In [15]:
for x in file_list:
  print(x)

Streaming output truncated to the last 5000 lines.
67889887_51559022.m4a
40283180_13170796.m4a
85540116_7945117.m4a
129766325_90799880.m4a
108280928_16300598.m4a
76142251_5545182.m4a
94691732_14122298.m4a
492703875_209778716.m4a
43160270_40066760.m4a
318416388_219870923.m4a
45591043_3302044.m4a
40246624_109052319.m4a
90760609_10409376.m4a
89081869_40809282.m4a
130332934_23306721.m4a
512387126_220939683.m4a
472169415_210676411.m4a
148788863_31061159.m4a
74229706_14999551.m4a
485321625_195639455.m4a
190296712_180843802.m4a
300917574_117459338.m4a
345903095_110723898.m4a
97682973_12305672.m4a
91657941_10104630.m4a
389504202_200806860.m4a
463293118_298484041.m4a
51954649_3272859.m4a
180555735_39540162.m4a
69587263_3724930.m4a
146225000_27217191.m4a
148480770_324782232.m4a
356749688_224990379.m4a
147183127_31255768.m4a
396238530_137645612.m4a
470059153_271084486.m4a
557611691_255776684.m4a
402670721_188812839.m4a
135925632_49877690.m4a
185022070_188686774.m4a
367307092_120646687.m4a
8204919

In [16]:
cd ..

/content/grace_data


In [17]:
cd ..

/content


Below is the script for the Data Generator. It takes in parameters corresponding to the data and then generates batches of data upon call (our batch size is set to one since we are dealing with audio data as described above, in the future we may look into reshaping methods).

We are not generating any test data right now, as you can see with the commented out 'y' variable and corresponding code. This would generate labels along with the training data.

In [186]:
import numpy as np
import keras

import random
import librosa
from os import listdir
from os.path import isfile, join

class DataGenerator(keras.utils.Sequence):
    'Generates data for Keras'
    def __init__(self, list_IDs, labels, batch_size, dim, n_channels,
                 n_classes, shuffle):
        'Initialization'
        self.dim = dim
        self.batch_size = batch_size
        self.labels = labels
        self.list_IDs = list_IDs
        self.n_channels = n_channels
        self.n_classes = n_classes
        self.shuffle = shuffle
        self.on_epoch_end()

    def __len__(self):
        'Denotes the number of batches per epoch'
        return int(np.floor(len(self.list_IDs) / self.batch_size))

    def __getitem__(self, index):
        'Generate one batch of data'
        # Generate indexes of the batch
        indexes = self.indexes[index*self.batch_size:(index+1)*self.batch_size]

        # Find list of IDs
        list_IDs_temp = [self.list_IDs[k] for k in indexes]

        # Generate data
        X = self.__data_generation(list_IDs_temp) #,y when other stuff is uncommented

        return X#, y

    def on_epoch_end(self):
        'Updates indexes after each epoch'
        self.indexes = np.arange(len(self.list_IDs))
        if self.shuffle == True:
            np.random.shuffle(self.indexes)

    def __data_generation(self, list_IDs_temp):
        'Generates data containing batch_size samples' # X : (n_samples, *dim, n_channels)
        # Initialization
        
        curr_len = 0
        for i,ID in enumerate(list_IDs_temp):
          print("Audio file name: " + str(ID))
          curr_len = len(self.load_audio('grace_data/amazing_grace/'+ID))
        print("Length of time series for this audio: " + str(curr_len))
        X = np.empty((self.batch_size, curr_len))
        #y = np.empty((self.batch_size), dtype=int)

        # Generate data
        for i, ID in enumerate(list_IDs_temp):
            # Store sample
            #self.load_audio('grace_data/amazing_grace/312087870_108215812.m4a')
            X[i,] = self.load_audio('grace_data/amazing_grace/'+ID)

            # Store class
            #y[i] = self.labels[ID]

        return X#, keras.utils.to_categorical(y, num_classes=self.n_classes)

    def load_audio(self,audio_file_path):
        """Load audio to numpy array and return it
        """
        x,sr = librosa.load(audio_file_path, sr = None)
        return x

In [187]:
print ("Number of audio files: " + str(len(file_list)))

Number of audio files: 17582


Construct a data generator with parameters corresponding to data, set labels to just one for now since we are not performing any classification at this moment.

In [188]:
dg = DataGenerator(file_list,["grace"]*len(file_list),1,(1,len(file_list)), 1,1,True)

Verify our loading of audio to a numpy array works by calling the function and checking the length.

In [189]:
dg.load_audio('grace_data/amazing_grace/312087870_108215812.m4a')

array([-1.2207031e-04, -1.2817383e-03, -2.0141602e-03, ...,
        3.0517578e-05,  0.0000000e+00,  3.0517578e-05], dtype=float32)

In [190]:
len(dg.load_audio('grace_data/amazing_grace/312087870_108215812.m4a'))

4215424

In [191]:
len(dg.load_audio('grace_data/amazing_grace/510603659_264818125.m4a'))

6718912

Finally, here is where we test our data generator. Call the __getitem__ method, the parameter which you pass is an index which corresponds to the batch you want to generate. For example, passing in 0 would mean you want the first batch of audio files' data.

In [192]:
dg.__getitem__(0)

Audio file name: 347364818_145648665.m4a
Length of time series for this audio: 4214912


array([[-0.00350952, -0.00430298, -0.00842285, ...,  0.00979614,
         0.00735474,  0.00424194]])

In [193]:
dg.__getitem__(1)

Audio file name: 283106758_82971743.m4a
Length of time series for this audio: 9104960


array([[ 0.02435303,  0.02084351,  0.01782227, ..., -0.00012207,
        -0.00015259, -0.00015259]])

In [196]:
dg.__getitem__(200)

Audio file name: 46394269_299487767.m4a
Length of time series for this audio: 8430784


array([[-0.00079346, -0.0010376 , -0.00146484, ...,  0.        ,
         0.        ,  0.        ]])

In [197]:
dg.__getitem__(3102)

Audio file name: 341539786_148095189.m4a
Length of time series for this audio: 1025920


array([[3.66210938e-04, 1.19018555e-03, 2.13623047e-03, ...,
        3.05175781e-05, 5.49316406e-04, 9.76562500e-04]])